name: Lint, Build and Push Docker Image

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
# Removed top-level permissions block

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use setup-python
        with:
          python-version: '3.9' # Match Dockerfile base image python version

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  build-and-push:
    name: Build and Push AMD64/ARM64 Image
    needs: lint # Add dependency on the lint job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permissions needed for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Updated version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 # Updated version
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Updated version
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64 # Added linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          # Add caching
          cache-from: type=gha
          cache-to: type=gha,mode=max
